/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary": "#ba9eff",
        "on-tertiary-fixed": "#3d2b00",
        "on-error-container": "#ffb2b9",
        "tertiary-dim": "#edb210",
        "on-secondary-fixed": "#5e006c",
        "primary-fixed-dim": "#a27cff",
        "on-background": "#ffffff",
        "inverse-on-surface": "#565555",
        "on-surface": "#ffffff",
        "surface-dim": "#0e0e0e",
        "surface-variant": "#262626",
        "on-tertiary-fixed-variant": "#614700",
        "primary-container": "#ae8dff",
        "outline-variant": "#484847",
        "surface": "#0e0e0e",
        "surface-bright": "#2c2c2c",
        "on-secondary": "#3d0047",
        "on-tertiary-container": "#563e00",
        "tertiary": "#ffd16f",
        "error-dim": "#d73357",
        "error-container": "#a70138",
        "on-error": "#490013",
        "surface-container-highest": "#262626",
        "inverse-primary": "#6e3bd7",
        "tertiary-container": "#fcc025",
        "background": "#0e0e0e",
        "secondary-fixed": "#fdbcff",
        "on-primary-container": "#2b006e",
        "on-secondary-fixed-variant": "#8c00a0",
        "inverse-surface": "#fcf9f8",
        "secondary-container": "#a200ba",
        "surface-container-high": "#20201f",
        "error": "#ff6e84",
        "surface-container": "#1a1a1a",
        "secondary-fixed-dim": "#faa6ff",
        "primary-fixed": "#ae8dff",
        "on-primary": "#39008c",
        "tertiary-fixed-dim": "#edb210",
        "secondary-dim": "#ec63ff",
        "surface-container-lowest": "#000000",
        "on-tertiary": "#614700",
        "on-primary-fixed-variant": "#370086",
        "outline": "#767575",
        "surface-container-low": "#131313",
        "on-secondary-container": "#fff5fa",
        "secondary": "#ec63ff",
        "on-surface-variant": "#adaaaa",
        "primary-dim": "#8455ef",
        "surface-tint": "#ba9eff",
        "tertiary-fixed": "#fcc025",
        "on-primary-fixed": "#000000"
      },
      fontFamily: {
        "headline": ["Epilogue"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
};
